### ISSUE TITLE
custom element doesn't exist: my-slider

### ISSUE THREAD

**Issue by joostvkempen** [usernein/tv-card#2]
**Checklist:**

- [ X] I updated to the latest version available
- [ X] I cleared the cache of my browser

**Release with the issue:** HA 2022.6.7 (docker version) / tv-card 0.4.0 installed from HACS

**Last working release (if known):** no earlier version tested

**Browser and Operating System:** Windows 10 / Chrome (all updated)

![image](https://user-images.githubusercontent.com/37901988/177057863-20fb2f44-a363-4e76-bfe8-03f49513601d.png)

**Description of problem:**  custom element doesn't exist: my-slider 

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:** also restarted HA, no difference

**Comment by usernein** [comment]
Ohh i'm sorry, i didn't make it clear that you need to install [slider-card](https://github.com/AnthonMS/my-cards#slider-card).
It's the card that tv-card uses as slider.

You just need to add `https://github.com/AnthonMS/my-cards.git` as custom repository with category: Lovelace (check the [detailed explanation](https://github.com/AnthonMS/my-cards/issues/17#issuecomment-1045213931))

**Comment by joostvkempen** [comment]
Ok, tnx! So this bug can be changed to a feature request to add this to the documentation ;-) 

And maybe for later on it's possible to integrate the my-slider code into the tv-card? All these cards depending on each other can make quit a mess in the configuration. I already see myself deleting the slider-card in a few months from now (what's this? don't use it? delete!) and having the same issue al over again ....

For now it is working, tnx!

**Comment by usernein** [comment]
> So this bug can be changed to a feature request to add this to the documentation ;-)

Definitely!

> maybe for later on it's possible to integrate the my-slider code into the tv-card?

Hmm yes yes. If possible, i can bundle my-slider into the repo. If not, make another new slider card for tv-card
I can also use [mushroom](https://github.com/piitaya/lovelace-mushroom) now since [v2.0.0](https://github.com/piitaya/lovelace-mushroom/releases/tag/v2.0.0) brought the ability to hide everything but the controls, transforming the card into a slider

**Comment by brewston** [comment]
Did you get this working @joostvkempen [joostvkempen](https://github.com/joostvkempen) ? I've added the slider repo (and can create standalone slider cards for lights etc) but when I define : 

`volume_row: slider`
in my remote card, nothing appears.

**Comment by usernein** [comment]
@brewston can you share your card config and a screenshot of the card not rendering the slider?
Also, can you check the javascript console logs on Dev Tools? There may be a clue

**Comment by brewston** [comment]
Sorry for not following up, it started working after one of the recent updates.

**Comment by usernein** [comment]
Ahhh nice! I guess it was related to #11
