### ISSUE TITLE
Unable to add new apps to apps-row

### ISSUE THREAD

**Issue by brewston** [usernein/tv-card#4]
**Checklist:**

- [x ] I updated to the latest version available
- [ x] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**

**Description of problem:**

I have a Samsung TV and use https://github.com/ollo69/ha-samsungtv-smart

I tried adding some other apps  like plex, disney+, prime  onto my remote card and they don't show up. I know that the samsungtv-smart recognises them as I have configured in a custom:mini-media-player card:

Example YAML from my card : 

```
apps_row:
  - prime
  - netflix
  - youtube
  - spotify
  - plex
```

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
Thanks for developing this, it looks great.

**Comment by brewston** [comment]
Thanks, that worked for plex, prime & disney+ - I needed to open the .svg file in a text editor to extract the string to paste into the yaml. But simpleicons doesn't have disney+  - I tried repeating the same process with .svg files from other source but it never renders . I will keep trying. Thanks.

**Comment by usernein** [comment]
Hey @brewston! Check out [v0.5.0](https://github.com/usernein/tv-card/releases/tag/v.0.5.0)
It lets you use other icon packs than MDI.

Now you can include those icons without touching svg paths, using the [simpleicons integration](https://github.com/vigonotion/hass-simpleicons):
```yaml
custom_sources:
  plex:
    icon: si:plex
    source: Plex
  prime:
    icon: si:primevideo
    source: Prime Video
```

**Comment by usernein** [comment]
> But simpleicons doesn't have disney+ - I tried repeating the same process with .svg files from other source but it never renders .

I also use Disney+ and i had the same issue. I don't have experience with SVG so i have no clue on why it doesn't renders

But i found [this](https://github.com/simple-icons/simple-icons/issues/2309) and [this](https://github.com/simple-icons/simple-icons/issues/7570#issuecomment-1176255251), saying that SimpleIcons (and probably any other pack) won't have Disney-related icons

**Comment by usernein** [comment]
Since v0.5.0, tv-card support all icon packs you can use in Home Assistant.
You can install custom-brand-icons through HACS and use phu:disney-plus as icon
